services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: appdb
    volumes:
      - mongodb-data:/data/db
      - ./init-scripts/mongodb/init-mongodb.js:/docker-entrypoint-initdb.d/init-mongodb.js:ro

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./init-scripts/postgres/init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql:ro
      - postgres-data:/var/lib/postgresql/data

#  kafkamq:
#    image: apache/kafka:latest
#    container_name: kafkamq
#    ports:
#        - 9092:9092
#    environment:


volumes:
  mongodb-data:
  postgres-data: